/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   render_docs_parser.c                               :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: maaugust <maaugust@student.42porto.com>    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/06/27 23:31:40 by maaugust          #+#    #+#             */
/*   Updated: 2026/07/03 15:59:44 by maaugust         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

/* ========================================================================== */
/* INCLUDES                                                                   */
/* ========================================================================== */

/* --------------------------- External Libraries --------------------------- */
#include "render.h"
#include "libft.h"
#include "mlx.h"

/* --------------------------- Internal Libraries --------------------------- */
#include <stdlib.h>
#include <unistd.h>

/* ========================================================================== */
/* FUNCTIONS                                                                  */
/* ========================================================================== */

/**
 * @fn static char **get_parser_text(void)
 * @brief Generates an array of strings detailing the parser syntax rules.
 * @details Utilizes libft's ft_split over a massive string block delimited 
 * by the '|' character. This allows the vast manual text to be compiled 
 * dynamically while maintaining strict Norm formatting constraints.
 * @return Null-terminated array of strings.
 */
static char	**get_parser_text(void)
{
	char	*str;

	str = "=== 1. ENVIRONMENT ===|R [width] [height]|A [ratio] [RGB]|"
		"C [pos] [dir] [fov] ap:[val] focal:[val]|"
		"L [pos] [ratio] [RGB] type:[spot/area] dir:[vec] in:[deg] out:[deg]|"
		"    uvec:[vec] ustep:[val] vvec:[vec] vstep:[val]|=== 2. SHAPES ===|"
		"sp [pos] [diam] [RGB]|pl [pos] [norm] [RGB]|"
		"cb [pos] [norm] [scale] [RGB]|cy [pos] [norm] [diam] [height] [RGB]|"
		"cn [pos] [norm] [diam] [height] [RGB]|"
		"to [pos] [norm] [major_diam] [minor_diam] [RGB]|"
		"tr [p1] [p2] [p3] [uv1] [uv2] [uv3] [RGB]|"
		"smt [p1] [p2] [p3] [n1] [n2] [n3] [uv1] [uv2] [uv3] [RGB]|"
		"obj [pos] [norm] [scale] [RGB] [file.obj]|"
		"=== 3. MATERIALS & TEXTURES ===|mat:[ambient],[diffuse],[specular],"
		"[shininess]|ref:[ratio]|glass:[refraction_index],[transparency]|"
		"chk:[RGB],[RGB]|str:[RGB],[RGB]|gra:[RGB],[RGB]|rng:[RGB],[RGB]|"
		"marble:[RGB],[RGB],[octaves],[vein_scale],[pattern_scale]|"
		"perlin:[RGB],[RGB],[octaves],[pattern_scale]|uv_chk:[width],[height],"
		"[RGB],[RGB]|img:[file.xpm]|bump:[file.xpm],[intensity],[epsilon]|"
		"dome:[file.xpm] (SPHERE)|skybox:[right.xpm],[left.xpm],[up.xpm],"
		"[down.xpm],[front.xpm],[back.xpm] (CUBE)|=== 4. MODIFIERS & CSG ===|"
		"rot:[x],[y],[z]|shr:[xy],[xz],[yx],[yz],[zx],[zy]|mov:[x,y,z]|"
		"caps:[0/1]|id:[name]|parent:[name]|grp [pos] [norm] [scale] id:[name]|"
		"csg [union/inter/diff] [left_id] [right_id] [pos] [norm] [scale]";
	return (ft_split(str, '|'));
}

/**
 * @fn static void print_parser_line(t_engine *engine, char *str, int drawn)
 * @brief Prints a single line of parser documentation.
 * @details Evaluates the first character. If it encounters a '=' (header tag), 
 * it shifts the text color to Cyan to create a distinct visual hierarchy in 
 * the UI.
 * @param engine The global engine context.
 * @param str    The literal string to print.
 * @param drawn  The vertical offset index.
 */
static void	print_parser_line(t_engine *engine, char *str, int drawn)
{
	int	c;

	c = 0xFFFFFF;
	if (str[0] == '=')
		c = 0x00FFFF;
	mlx_string_put(engine->mlx.mlx_ptr, engine->mlx.win_ptr, 100,
		150 + (drawn * 30), c, str);
}

/**
 * @fn static void free_split(char **str)
 * @brief Cleans up the dynamically generated parser syntax array.
 * @details Safely frees every string allocation generated by ft_split.
 * @param str The double pointer to free.
 */
static void	free_split(char **str)
{
	int	i;

	if (!str)
		return ;
	i = -1;
	while (str[++i])
		free(str[i]);
	free(str);
}

/**
 * @fn void render_docs_parser(t_engine *engine)
 * @brief Handles the rendering and scrolling logic of the syntax manual.
 * @details Restricts the text drawing loop to exactly 12 lines to prevent 
 * overlapping the UI bounds. Dynamically calculates the starting index 
 * based on the cursor to facilitate seamless scrolling pagination.
 * @param engine The global engine context.
 */
void	render_docs_parser(t_engine *engine)
{
	char	**str;
	int		start;
	int		drawn;
	int		i;

	str = get_parser_text();
	if (!str)
	{
		engine->exit_code = MALLOC;
		ft_putendl_fd("Error\nMalloc failed in BIOS docs", STDERR_FILENO);
		exit_program(engine);
	}
	start = engine->bios.cursor_index;
	drawn = 0;
	i = -1;
	while (str[++i] && drawn < 12)
		if (i >= start)
			print_parser_line(engine, str[i], drawn++);
	free_split(str);
}
